#spring:
#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password:
#server:
#  port: 8081
camel.openapi:
  routes:
    client-service:
      pathToSpec: classpath:client-service/client-service-spec.yaml
      params:
        basePath: client-service
        host: http://localhost:8081
      operationsIds:
        - createKeycloakClient
        - createClient
        - deleteKeycloakClient